# Generated by Django 3.1.5 on 2021-01-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Partner',
            fields=[
                ('dl_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('available', models.BooleanField(default=True)),
                ('two_wheeler', models.BooleanField(default=False)),
                ('heavy_motor_vehicle', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('slot_number', models.IntegerField(max_length=1)),
                ('delivery_address', models.IntegerField(max_length=40)),
                ('delivery_status_code', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Class',
            fields=[
                ('vehicle_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('first_slot', models.BooleanField(default=False)),
                ('second_slot', models.BooleanField(default=False)),
                ('third_slot', models.BooleanField(default=False)),
                ('fourth_slot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Detail',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.vehicle_class')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Detail',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status_code', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.pending_order')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_app.delivery_partner')),
            ],
        ),
        migrations.CreateModel(
            name='Delivered_Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('slot_number', models.IntegerField()),
                ('delivery_address', models.IntegerField()),
                ('delivery_feedback', models.CharField(max_length=100)),
                ('delivery_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.delivery_detail')),
            ],
        ),
    ]
